const route = require('express').Router()
const disposal = require('../controllers/disposal')

route.get('/get', disposal.getDisposal)
route.get('/cart', disposal.getCartDisposal)
route.patch('/approval', disposal.getApproveDisposal)
route.patch('/detail', disposal.getDetailDisposal)
route.post('/add/:no', disposal.addDisposal)
route.post('/sell', disposal.addSell)
route.delete('/delete/:asset', disposal.deleteDisposal)
route.post('/img/:asset', disposal.uploadImage)
route.post('/submit', disposal.submitDisposal)
route.patch('/subfin', disposal.submitDisposalFinal)
route.patch('/approve', disposal.approveDisposal)
route.patch('/reject', disposal.rejectDisposal)
route.patch('/update/:id/:tipe', disposal.updateDisposal)
route.patch('/doc', disposal.getDocumentDis)
route.post('/upload/:id', disposal.uploadDocument)
route.patch('/docapp/:id', disposal.approveDokumen)
route.patch('/docrej/:id', disposal.rejectDokumen)
route.patch('/setuju/submit', disposal.submitSetDisposal)
route.get('/setuju/get', disposal.getSetDisposal)
route.patch('/setuju/getapp', disposal.getApproveSetDisposal)
route.patch('/setuju/approve', disposal.approveSetDisposal)
route.patch('/setuju/reject', disposal.rejectSetDisposal)
route.patch('/eks/submit', disposal.submitEksDisposal)
route.patch('/taxfin/submit', disposal.submitTaxFin)
route.patch('/final/submit', disposal.submitFinal)
route.patch('/purch/submit', disposal.submitPurch)
route.patch('/taxfin/rej/:no', disposal.rejectTaxFin)
route.patch('/taxfin/edit/:no', disposal.submitEditTaxFin)
route.patch('/asset', disposal.updateStatus)
route.get('/purch/get', disposal.getDocumentPurch)
route.patch('/editdis/:no', disposal.submitEditDis)
route.patch('/rejeks', disposal.rejectEks)
route.patch('/editeks', disposal.submitEditEks)
route.patch('/apprev/:id/:type', disposal.appRevisi)
route.patch('/subrev', disposal.submitRevisi)
route.patch('/gennoset', disposal.genNoSetDisposal)

module.exports = route
