const route = require('express').Router()
const mutasi = require('../controllers/mutasi')

route.post('/add/:no/:plant', mutasi.addMutasi)
route.get('/get', mutasi.getMutasi)
route.get('/cart', mutasi.getDataCart)
route.delete('/del/:id', mutasi.deleteItem)
route.post('/submit', mutasi.submitMutasi)
route.post('/subfin', mutasi.submitMutasiFinal)
route.patch('/detail', mutasi.getDetailMutasi)
route.patch('/approve', mutasi.getApproveMut)
route.patch('/update', mutasi.updateMutasi)
route.patch('/app', mutasi.approveMutasi)
route.patch('/rej', mutasi.rejectMutasi)
route.patch('/rejeks', mutasi.rejectEksekusi)
route.get('/rec', mutasi.getMutasiRec)
route.patch('/appdoc/:id', mutasi.approveDokumen)
route.patch('/rejdoc/:id', mutasi.rejectDokumen)
route.post('/upload/:id', mutasi.uploadDocument)
route.patch('/doc', mutasi.getDocument)
route.patch('/status/:id/:stat', mutasi.updateBudget)
route.patch('/eks', mutasi.submitEks)
route.patch('/budget', mutasi.submitBudget)
route.patch('/upstat/:id', mutasi.updateEksekusi)
route.patch('/changeDate', mutasi.updateDate)
route.patch('/subedit', mutasi.submitEditMutasi)
route.delete('/delapp', mutasi.deleteApprove)
route.patch('/apprev/:id/:type', mutasi.appRevisi)
route.patch('/subrev', mutasi.submitRevisi)
route.patch('/upreason', mutasi.updateReason)
route.patch('/scan', mutasi.scanQrMutasi)

module.exports = route
