const route = require('express').Router()
const mutasi = require('../controllers/mutasi')

route.post('/add/:id/:plant', mutasi.addMutasi)
route.get('/get', mutasi.getMutasi)
route.delete('/del/:no', mutasi.deleteItem)
route.post('/submit', mutasi.submitMutasi)
route.post('/subfin', mutasi.submitMutasiFinal)
route.patch('/detail', mutasi.getDetailMutasi)
route.patch('/approve', mutasi.getApproveMut)
route.patch('/update', mutasi.updateMutasi)
route.patch('/app', mutasi.approveMutasi)
route.patch('/rej', mutasi.rejectMutasi)
route.patch('/rejeks', mutasi.rejectEksekusi)
route.get('/rec', mutasi.getMutasiRec)
route.patch('/docrej/:id', mutasi.rejectDokumen)
route.patch('/doc', mutasi.getDocumentMut)
route.patch('/status/:id/:stat', mutasi.updateBudget)
route.patch('/eks', mutasi.submitEks)
route.patch('/budget', mutasi.submitBudget)
route.patch('/upstat/:id', mutasi.updateEksekusi)
route.patch('/changeDate', mutasi.updateDate)
route.patch('/subedit', mutasi.submitEditMutasi)
route.delete('/delapp', mutasi.deleteApprove)

module.exports = route
