const route = require('express').Router()
const mutasi = require('../controllers/mutasi')

route.post('/add/:no/:plant', mutasi.addMutasi)
route.get('/get', mutasi.getMutasi)
route.delete('/del/:no', mutasi.deleteItem)
route.post('/submit', mutasi.submitMutasi)
route.get('/detail/:no/:tipe', mutasi.getDetailMutasi)
route.get('/approve/:no/:nama', mutasi.getApproveMut)
route.patch('/app/:no', mutasi.approveMutasi)
route.patch('/rej/:no', mutasi.rejectMutasi)
route.patch('/rejeks/:no', mutasi.rejectEksekusi)
route.get('/rec', mutasi.getMutasiRec)
route.patch('/docrej/:id', mutasi.rejectDokumen)
route.get('/doc/:no/:nomut', mutasi.getDocumentMut)
route.patch('/status/:id/:stat', mutasi.updateBudget)
route.get('/eks/:no', mutasi.submitEks)
route.get('/budget/:no', mutasi.submitBudget)
route.patch('/upstat/:id', mutasi.updateEksekusi)

module.exports = route
