const route = require('express').Router()
const pengadaan = require('../controllers/pengadaan')

route.get('/get', pengadaan.getPengadaan)
route.get('/track', pengadaan.tracking)
route.patch('/approve', pengadaan.getApproveIo)
route.patch('/document', pengadaan.getDocumentIo)
route.patch('/appdoc/:id', pengadaan.approveDokumen)
route.patch('/rejdoc/:id', pengadaan.rejectDokumen)
route.post('/upload/:id', pengadaan.uploadDocument)
route.post('/post', pengadaan.postApi)
route.get('/check', pengadaan.cekApi)
route.patch('/detail', pengadaan.getDetail)
route.patch('/temp', pengadaan.getTempAsset)
route.get('/tesemail', pengadaan.tesEmail)
route.patch('/upasset/:id', pengadaan.updateDataIo)
route.patch('/uptemp/:id', pengadaan.updateTemp)
route.patch('/upnoio', pengadaan.updateNoIo)
route.patch('/noasset/:id', pengadaan.updateNoAsset)
route.patch('/subasset', pengadaan.submitIsAsset)
route.patch('/subbudget', pengadaan.submitBudget)
route.patch('/subeks', pengadaan.submitEks)
route.patch('/subrev', pengadaan.submitRevisi)
route.patch('/app', pengadaan.approveIo)
route.patch('/rej', pengadaan.rejectIo)
route.post('/master', pengadaan.uploadMasterTemp)
route.patch('/del', pengadaan.deleteTransaksi)
route.get('/cart', pengadaan.getDataCart)
route.patch('/asetsap', pengadaan.generateAssetSap)

// route.patch('/subcart', pengadaan.submitCart)
route.patch('/submit', pengadaan.submitIo)
route.patch('/subfinio', pengadaan.submitIoFinal)

route.post('/addcart', pengadaan.addCart)
route.patch('/upcart/:id', pengadaan.updateCart)
route.patch('/apprev/:id', pengadaan.appRevisi)
route.delete('/delcart/:id', pengadaan.deleteCart)
route.get('/report', pengadaan.getReport)
route.patch('/send', pengadaan.podsSend)
route.post('/rec', pengadaan.podsReceive)
route.get('/doccart/:id', pengadaan.getDocumentCart)
route.patch('/appall', pengadaan.approveAll)
route.patch('/upreason', pengadaan.updateReason)
route.get('/rev', pengadaan.getRevisi)
route.get('/tpods', pengadaan.tesApiPods)
route.patch('/subnot', pengadaan.submitNotAsset)

// remove sparator all ajuan asset
route.patch('/remspar', pengadaan.removeSpar)

// remove underline in no ref
route.patch('/underline', pengadaan.removeUnderline)

module.exports = route
