const route = require('express').Router()
const pengadaan = require('../controllers/pengadaan')

route.get('/get', pengadaan.home)
route.get('/approve/:no', pengadaan.getApproveIo)
route.get('/document/:no', pengadaan.getDocumentIo)
route.patch('/appdoc/:id', pengadaan.approveDokumen)
route.patch('/rejdoc/:id', pengadaan.rejectDokumen)
route.post('/upload/:id', pengadaan.uploadDocument)
route.post('/post', pengadaan.postApi)
route.get('/check', pengadaan.cekApi)
route.get('/detail/:no', pengadaan.getDetail)
route.get('/temp/:no', pengadaan.getTempAsset)
route.get('/tesemail', pengadaan.tesEmail)
route.patch('/upasset/:id', pengadaan.updateDataIo)
route.patch('/uptemp/:id', pengadaan.updateTemp)
route.patch('/upnoio/:no', pengadaan.updateNoIo)
route.patch('/noasset/:id', pengadaan.updateNoAsset)
route.patch('/subasset/:no', pengadaan.submitIsAsset)
route.patch('/subbudget/:no', pengadaan.submitBudget)
route.patch('/subeks/:no', pengadaan.submitEks)
route.patch('/app/:no', pengadaan.approveIo)
route.patch('/rej/:no', pengadaan.rejectIo)
route.post('/master/:no', pengadaan.uploadMasterTemp)
route.patch('/del/:no', pengadaan.deleteTransaksi)
route.get('/cart', pengadaan.getDataCart)
route.patch('/subcart', pengadaan.submitCart)
route.post('/addcart', pengadaan.addCart)
route.patch('/upcart/:id', pengadaan.updateCart)
route.delete('/delcart/:id', pengadaan.deleteCart)
route.get('/report', pengadaan.getReport)
route.get('/send/:no', pengadaan.podsSend)
route.post('/rec', pengadaan.podsReceive)
route.get('/doccart/:no', pengadaan.getDocumentCart)
route.patch('/appall', pengadaan.approveAll)
route.patch('/uprecent/:no', pengadaan.updateAlasan)
route.get('/rev', pengadaan.getRevisi)

module.exports = route
