const route = require('express').Router()
const stock = require('../controllers/stock')

route.get('/submit', stock.submitStock)
route.patch('/subfinal', stock.submitStockFinal)
route.get('/get', stock.getStockAll)
route.get('/report', stock.getReportAll)
route.patch('/detail', stock.getDetailStock)
route.get('/item/:id', stock.getDetailItem)
route.delete('/delete/:id', stock.deleteStock)
route.get('/approve/:id', stock.getApproval)
route.patch('/app', stock.approveStock)
route.patch('/rej', stock.rejectStock)
route.post('/pict/:no', stock.uploadPicture)
route.post('/img/:no', stock.uploadImage)
route.post('/status/add', stock.addStatus)
route.get('/status/get', stock.getStatus)
route.get('/status/all', stock.getStatusAll)
route.post('/upload/:id', stock.uploadDocument)
route.get('/doc/:no/:id', stock.getDocument)
route.get('/cekdoc/:no/:id', stock.getDocument)
route.get('/area', stock.getStockArea)
route.patch('/update/:id', stock.updateStock)
route.patch('/subrev/:id', stock.submitRevisi)
route.patch('/apprev/:id', stock.appRevisi)
route.post('/add', stock.addStock)
route.patch('/subaset', stock.submitAsset)
route.patch('/export', stock.exportStock)
route.patch('/insert/img', stock.updateImageStock)

module.exports = route
